---
Name: fromholdio-superlinker
---

Fromholdio\SuperLinker\Model\SuperLink:
  extensions:
    - 'Fromholdio\SuperLinker\Extensions\EmailLink'
    - 'Fromholdio\SuperLinker\Extensions\ExternalLink'
    - 'Fromholdio\SuperLinker\Extensions\FileLink'
    - 'Fromholdio\SuperLinker\Extensions\NullLink'
    - 'Fromholdio\SuperLinker\Extensions\PhoneLink'
    - 'Fromholdio\SuperLinker\Extensions\SiteTreeLink'
  disallowed_types:
    - nolink
  types:
    email:
      sort: 2
    external:
      sort: 3
    phone:
      sort: 4
    nolink:
      sort: 5
    globalanchor:
      sort: 7
    system:
      sort: 6
    sitetree:
      sort: 0
    file:
      sort: 1

Fromholdio\SuperLinker\Model\VersionedSuperLink:
  extensions:
    - 'Fromholdio\SuperLinker\Extensions\EmailLink'
    - 'Fromholdio\SuperLinker\Extensions\ExternalLink'
    - 'Fromholdio\SuperLinker\Extensions\FileLink'
    - 'Fromholdio\SuperLinker\Extensions\NullLink'
    - 'Fromholdio\SuperLinker\Extensions\PhoneLink'
    - 'Fromholdio\SuperLinker\Extensions\SiteTreeLink'
  disallowed_types:
    - nolink
  types:
    email:
      sort: 2
    external:
      sort: 3
    phone:
      sort: 4
    nolink:
      sort: 5
    globalanchor:
      sort: 7
    system:
      sort: 6
    sitetree:
      sort: 0
    file:
      sort: 1

---
Only:
  moduleexists:
    - 'fromholdio/silverstripe-systemlinks'
---

Fromholdio\SuperLinker\Model\SuperLink:
  extensions:
    - 'Fromholdio\SuperLinker\Extensions\SystemLink'

Fromholdio\SuperLinker\Model\VersionedSuperLink:
  extensions:
    - 'Fromholdio\SuperLinker\Extensions\SystemLink'

---
Only:
  moduleexists:
    - 'fromholdio/silverstripe-globalanchors'
---

Fromholdio\SuperLinker\Model\SuperLink:
  extensions:
    - 'Fromholdio\SuperLinker\Extensions\GlobalAnchorLink'

Fromholdio\SuperLinker\Model\VersionedSuperLink:
  extensions:
    - 'Fromholdio\SuperLinker\Extensions\GlobalAnchorLink'
